#This is properties file for pusher-backend
#created by : kotekaman
#created at : February, 18th 2019
[server]
port="3030"

[postgres]
url="35.240.138.22"
Port="5432"
db="postgres"
user="postgres"
password="root123"

[mail]
smtp="smtp.gmail.com"
port="587"
from="ffixteam@gmail.com"
password="8XutyW7MP8xN3hJ"

[oauth]
rurl="http://localhost:3000/callback"
clientid="650163288793-lk408f80nguqol22arr28jidtpggg2hu.apps.googleusercontent.com"
clientsecret="M64xx4HiZ2PbQ5V1mH7Bon2f"